### ISSUE TITLE
built-in validation classes

### ISSUE THREAD

**Issue by spectrum48k** [modxcms/xpdo#116]
Built-in validation classes do not return true / false , but return a null, so their use does not allow validation using the method as specified in the documentation
If ($ validator-> validate () == false) {... some error handling}

**Comment by opengeek** [comment]
Last I checked `null == false` (but `null !== false`) in PHP. Can you clarify what you are reporting here, please?

**Comment by spectrum48k** [comment]
xPDOMaxLengthValidationRule::isValid(), xPDOMinValueValidationRule::isValid(), xPDOMaxValueValidationRule::isValid()   have no 'return $result'
I mean return of null successfully passes validation because used 'strict' mode here
$this->results[$column]= !in_array(false, $columnResults, true) ? true : false;
(xpdovalidator.class.php:111, xpdovalidator.class.php:120)

**Comment by opengeek** [comment]
Wow, good catch. Getting that patched up now. Thanks for the clarification.

**Comment by opengeek** [comment]
Fixed in 3f6153782dcb3fad008469b1028947132c12c878.
