### ISSUE TITLE
xPDOObject.php php7.2 error depricated each()

### ISSUE THREAD

**Issue by Dmi3yy** [modxcms/xpdo#132]
http://take.ms/A8ygF

**Comment by Mark-H** [comment]
This is something we should fix sooner rather than later, but @dmi3yy why did you put that in a screenshot and not just in the message itself?

**Comment by Dmi3yy** [comment]
I received a bug report from another programmer in the form of a screenshot. 
Then test code and write issue )

**Comment by opengeek** [comment]
Yes, I will get this fixed for all branches as soon as possible.

**Comment by alroniks** [comment]
All PRs merged, this issue may be closed.
