### ISSUE TITLE
Missing quotable phptype text

### ISSUE THREAD

**Issue by sdrenth** [modxcms/xpdo#144]
You've already added json and array phptypes in this commit, but I'm missing the 'text' type which is causing issues in PHP 7.2.

So it should be:
```
protected $_quotable= array ('string', 'password', 'date', 'datetime', 'timestamp', 'time', 'json', 'array', 'text');
```

**Comment by opengeek** [comment]
There is no `text` PHP type.

**Comment by Jako** [comment]
Could those wrong phptypes (or dbtypes) be logged during the class generation?
