### ISSUE TITLE
Wrong date format

### ISSUE THREAD

**Issue by jgulledge19** [modxcms/xpdo#158]
https://github.com/modxcms/xpdo/blob/10b165d407f34b2013eec7a6266f9c171c1afcfb/xpdo/om/xpdoobject.class.php#L1020

It looks like the referenced code is using `date('Y-m-d H:M:S')` which looks incorrect based on [PHP date](https://php.net/manual/en/function.date.php) documents and I believe it should be `date('Y-m-d H:i:s')`. 

The existing format appears to match the [strftime](https://www.php.net/manual/en/function.strftime.php) function that is just a few lines down.

**Comment by Jako** [comment]
It should be a small s in `date('Y-m-d H:i:s', $ts);` in the fix.
