### ISSUE TITLE
Request V3: Add Timezone to MODX\Revolution\modUserProfile

### ISSUE THREAD

**Issue by wshawn** [modxcms/xpdo#160]
table: modx_user_attributes

Something like: 
```
field key="timezone" dbtype="varchar" precision="50" phptype="string" null="false" default=""/>
```
This may have been a simple oversight , but in situations where sites serve an international client base, the local PHP and MySQL are probably set to UTC, so if daily content is supposed to change at "midnight" which midnight is it supposed to use? From the visitor's perspective, it should be theirs. In the U.S. the server midnight currently hits from 2PM - 8PM depending on Timezone.

**Comment by opengeek** [comment]
This is not an xPDO issue.
