### ISSUE TITLE
Minor, but can we get the return type corrected?

### ISSUE THREAD

**Issue by wshawn** [modxcms/xpdo#163]
https://github.com/modxcms/xpdo/blob/989e27cf4188d763755e9821a6f276c0b40cff85/src/xPDO/xPDO.php#L1046

**Comment by Mark-H** [comment]
`xPDOObject|null`?

**Comment by wshawn** [comment]
Yes, please.

**Comment by JoshuaLuckers** [comment]
@opengeek LGTM! 😋
