### ISSUE TITLE
[bug] [v3] Extended objects missing parent indexes

### ISSUE THREAD

**Issue by smaddock** [modxcms/xpdo#179]
In my schema I'm using a lot of `extends="Parent\Class"` If I define an index in a parent, that index is not included in the child class. If I define a field in a parent, I can't use that field in an index of the child. (I was trying to figure out why `getObjectGraph()` wasn't working, and traced it back to `getPK()` returning null on classes that should have a primary key defined if traced back through the extended model classes.)

Running xPDO 3.0@dev, PHP 7.3.5/7.3.11

### test.mysql.schema.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<model package="ExtendedIndex\Test" baseClass="xPDO\Om\xPDOObject" platform="mysql" defaultEngine="InnoDB" version="3.0">

    <object class="ClassA" extends="xPDO\Om\xPDOObject">
        <field key="id" dbtype="int" attributes="unsigned" phptype="integer" />

        <index name="PRIMARY" primary="true">
            <column key="id" />
        </index>
    </object>

    <object class="ClassB" table="b_table" extends="ExtendedIndex\Test\ClassA">
        <!--this object/class/table will have no PK-->
    </object>

    <object class="ClassC" extends="xPDO\Om\xPDOObject">
        <field key="code" dbtype="int" attributes="unsigned" phptype="integer" />
    </object>

    <object class="ClassD" table="d_table" extends="ExtendedIndex\Test\ClassC">
        <field key="type" dbtype="int" attributes="unsigned" phptype="integer" />

        <index name="PRIMARY" primary="true">
            <column key="code" />
            <column key="type" />
        </index>
        <!--this object/class/table will have a PK of only "type"-->
    </object>

</model>
```

**Comment by smaddock** [comment]
Intrestingly, the `ExtendedIndex\Test\mysql\ClassD.php` definition does list both columns under the index, so it appears to be an issue with `getPK()` not the model files.

**Comment by Mark-H** [comment]
AFAIK you need to add `inherit="single"` on the parent model for that to work. Alto I don't personally use the graph methods much, so I could certainly be wrong if this issue is specific to that.

**Comment by smaddock** [comment]
`inherit="single"` creates an STI table on the parent... I need different tables for each child (inherit multi). The issue is definitely with the getPK method (or some subprocess thereof) which I believe affects more than just the graph methods.

**Comment by Mark-H** [comment]
STI?

**Comment by Mark-H** [comment]
Having `inherit="single"` tells xPDO to add the parent fields to the descendants: 

https://github.com/modxcms/xpdo/blob/be54eb1d18a70351aea4bdf06b1cdda8bbba1e93/src/xPDO/xPDO.php#L1423-L1433

**Comment by smaddock** [comment]
I will test this shortly, but I thought `inherit="single"` was exclusively for single table inheritance (STI), where the parent DB table stores the data for all the child “classes”. The default behavior which I'm using is multi table inheritance (MTI), the fields are all correctly inheriting just not the indexes.

**Comment by smaddock** [comment]
Tested: adding `inherit="single"` to ClassA and ClassC in the schema above had no effect on `getPK()`.

**Comment by opengeek** [comment]
@smaddock — can you add the `index="pk"` attribute to your primary key field definitions? I think that is why it is failing.

**Comment by smaddock** [comment]
That fixed it on the test schema above. Will try it on our production schema next. I assumed like in MySQL that indexes could be defined inline or out of line, which is why I didn't include it originally... yay assuming. 🤦

**Comment by smaddock** [comment]
`getPK()` is resolving now, but the graph is still failing. First think I've noticed is `_pktype` is still blank in the xPDOObject... will see if I can dig further.

**Comment by smaddock** [comment]
For the graph, `$parentObj->_relatedObjects` is getting populated, but `$parentObj->childAlias` is null.

**Comment by smaddock** [comment]
Which I didn't have `OPT_HYDRATE_RELATED_OBJECTS` set. 🤦 🤦

**Comment by smaddock** [comment]
Yeah it's all working now. The `index="pk"` was the key. Thanks @opengeek and @Mark-H !!!
