### ISSUE TITLE
writeSchema vs xPDO 3.

### ISSUE THREAD

**Issue by Jako** [modxcms/xpdo#222]
The writeSchema method in xPDO 3 does not create a valid scheme for xPDO 3. 

opengeek stated on Slack: "that’s all still 2.x schema-ish".

**Comment by Jako** [comment]
An example generated scheme:
[testpackage.mysql.schema.xml.txt](https://github.com/modxcms/xpdo/files/7981007/testpackage.mysql.schema.xml.txt)

**Comment by opengeek** [comment]
I believe this was implemented in ce9e1a3153cc0b79a38eeaf605399ac4263aeef1
