### ISSUE TITLE
incorrect type specified for $obj in \modPackageBuilder->createVehicle phpdocs

### ISSUE THREAD

**Issue by netProphET** [modxcms/xpdo#24]
phpdocs for \modPackageBuilder->createVehicle state $obj is expected to be an xPDOObject. I know that it can also be an array, but not sure if there are other types.

Proposing either of the following:

```@param xPDOObject|array $obj The xPDOObject being abstracted as a vehicle.```
 or 
```@param mixed $obj The xPDOObject being abstracted as a vehicle.```

**Comment by opengeek** [comment]
Being addressed in https://github.com/modxcms/revolution/pull/12631
