### ISSUE TITLE
Filter/Escape reserved words in MySQL 8?

### ISSUE THREAD

**Issue by jenswittmann** [modxcms/xpdo#254]
I found a Bug an a fresh Ubuntu installation with MySQL 8 and Formalicious. Its already documented here: https://github.com/Sterc/Formalicious/issues/4

To get the steps from the form, there is a sorting like `rank`:

https://github.com/Sterc/Formalicious/blob/8ebad78bc9d1e3fa7847161347066ab500a2d3c0/core/components/formalicious/model/formalicious/formaliciousform.class.php#L61

The generated query is the following:

```
SELECT `FormaliciousStep`.`id` AS `FormaliciousStep_id`, `FormaliciousStep`.`form_id` AS `FormaliciousStep_form_id`, `FormaliciousStep`.`title` AS `FormaliciousStep_title`, `FormaliciousStep`.`description` AS `FormaliciousStep_description`, `FormaliciousStep`.`button` AS `FormaliciousStep_button`, `FormaliciousStep`.`rank` AS `FormaliciousStep_rank`, `FormaliciousStep`.`published` AS `FormaliciousStep_published` FROM `wop_formalicious_steps` AS `FormaliciousStep` WHERE `FormaliciousStep`.`form_id` = 1 ORDER BY rank ASC
```

So the ORDER BY rank must be in backticks to be valid in MySQL 8. Because its a resevered word: https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-R

Is there a way to fixes the problem in xpdo rather then in the plugins code?

I use MODX 2.8.6 and Formalicious 2.0.5.

Maybe this is fixed in MODX 3.0.4, but it also should be fixed in MODX 2 i think 😸

**Comment by opengeek** [comment]
You MUST call escape on the field name when passing it to the sortby value:

```$criteria->sortby($this->xpdo->escape('rank'), 'ASC');```

xPDO does not do this for you, or it would not be possible to use expressions or fields from other aliases in the query within the ORDER BY clause.

**Comment by jenswittmann** [comment]
Thanks for the explanation! Then it should be resolved in https://github.com/Sterc/Formalicious/issues/4.
