### ISSUE TITLE
Feature Request: AES_ENCRYPT (or other MySQL functions) via xPDO

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/xpdo#31]
I have been trying *(without luck)* to ```AES_ENCRYPT``` data being inserted into MySQL via ```$modx->parseBindings()```. The resulting record gets inserted, but the MySQL function is not evaluated, rather treated as a string, logging the raw data...

It would be nice if there was a way to identify an xPDOQuery operator / keyword trigger to instead evaluate the function inside MySQL.

I have not tried using other functions, but I would imagine there could be others that fall under this same scenario?

**Comment by opengeek** [comment]
You can use MySQL functions though xPDO, but parseBindings() is intended to approximate the process the server will perform when the query is executed, but will not be able to get the actual results of MySQL-side calculations AFAIK. If you know of a way to make this happen, please reopen with an example or some references.
