### ISSUE TITLE
Respect index column length attributes

### ISSUE THREAD

**Issue by bertoost** [modxcms/xpdo#33]
When creating indexes in the xml schema files, you can set a length attribute on the fields. For example:

<pre>&lt;index alias="pattern_context" name="pattern_context" primary="false" unique="true"&gt;
    &lt;column key="pattern" length="100" collation="A" null="false" /&gt;
    &lt;column key="context_key" length="100" collation="A" null="true" /&gt;
&lt;/index&gt;</pre>

In this case it's a unique index.

This results in a create table query with this index line:

<pre>UNIQUE INDEX `pattern_context` (`pattern`, `context_key`)</pre>

But this should be:

<pre>UNIQUE INDEX `pattern_context` (`pattern` (100), `context_key` (100))</pre>

Above unique index fails because the length of those normal field definition are to long (255). But it could work if the length attribute on the index columns are respected in the query.

**Comment by opengeek** [comment]
FWIW, this should work, but your model must be version="1.1" or later, or it uses the legacy index definitions which did not specify length metadata.
