### ISSUE TITLE
xpdo.class.php: getCount() function returns zero in absence of primary key

### ISSUE THREAD

**Issue by javadecaf** [modxcms/xpdo#43]
Uncovered this issue(?) while using xPDO on SQL Server as a bridge to legacy dBase files. Since this type of table lacks a primary key, the condition on line 1005 evaluates to null. My query also contained no "groupby" or "having" clause, so it was structured according to line 1021, resulting in an invalide "COUNT(DISTINCT *)" syntax. (Not sure if this is invalid in SQL or not, but it causes T-SQL to throw an error.)  My temp fix was to move the "DISTINCT" keyword to line 1009: 

$expr= 'DISTINCT '.$this->getSelectColumns($className, $query->getAlias(), '', $pk);

leaving line 1021 as:

$query->select(array ("COUNT({$expr})"));

I am not anything like an expert in this field, so it's possible that change will mess something else up.  It's also possible that this is a case of some sort of user error, and not a bug at all, in which case please enlighten me.  Thanks!

**Comment by opengeek** [comment]
I know this is an old issue, but wanted to reply anyway — there are quite a few things in xPDO that will not work without a primary key defined because there must be a unique column value (or a combination of several) that can be used to identify the object that is instantiated.
