### ISSUE TITLE
[3.x] PSR-4 friendly

### ISSUE THREAD

**Issue by theboxer** [modxcms/xpdo#80]
Currently it's not possible to generate Classes to specific folder without creating a folder for namespace (package).

When I have in my composer.json:

``` json
"autoload": {
        "psr-4": {
            "MyApp\\": ["src/"]
        }
    }
```

and I use as a package `MyApp/Model` I'd like to generate all my classes directly to `src/Model/` directory.

**Comment by wshawn** [comment]
I would REALLY like to see PSR-4 compliance in the core. Zend lists hundreds of compliance issues. Namespaces are an excellent issue Boxer. Thank you.
